name: smart_garage_final_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0
#------------------ Packages -------------------#
dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.7
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  lottie: ^3.3.1
  percent_indicator: ^4.2.4
  provider: ^6.1.4
  rename: ^3.0.2
  shared_preferences: ^2.5.2
  slide_to_act: ^2.0.2

#------------------ ./ Packages End -------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

  flutter_lints: ^5.0.0
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null

flutter:
  uses-material-design: true
  #------------------ Local Assets -------------------#
  assets:
    - assets/animation/
    - assets/images/
    - assets/icons/app_icon.png
  #------------------ Local Fonts -------------------#
  fonts:
    - family: Stinger
      fonts:
        - asset: assets/fonts/StingerWideTrial-Italic.ttf
    #         style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
