// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLmk8X_l91S4wVX3zUiGb9Y6LgEN-gNM',
    appId: '1:679017665841:web:5c29c60ca3fd3359b44c10',
    messagingSenderId: '679017665841',
    projectId: 'go-park-df349',
    authDomain: 'go-park-df349.firebaseapp.com',
    storageBucket: 'go-park-df349.firebasestorage.app',
    measurementId: 'G-P7126CZVB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6hsnXvXBsigd8OX0LrpxG83iNeaM7bs',
    appId: '1:679017665841:android:b05ef44db85e1ad9b44c10',
    messagingSenderId: '679017665841',
    projectId: 'go-park-df349',
    storageBucket: 'go-park-df349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4up7QEPUEMvJDFaPZI5aF1wz-ciTQIdg',
    appId: '1:679017665841:ios:df98cbf3bd5cf0f2b44c10',
    messagingSenderId: '679017665841',
    projectId: 'go-park-df349',
    storageBucket: 'go-park-df349.firebasestorage.app',
    iosBundleId: 'tawakycreation.smartGarageFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4up7QEPUEMvJDFaPZI5aF1wz-ciTQIdg',
    appId: '1:679017665841:ios:df98cbf3bd5cf0f2b44c10',
    messagingSenderId: '679017665841',
    projectId: 'go-park-df349',
    storageBucket: 'go-park-df349.firebasestorage.app',
    iosBundleId: 'tawakycreation.smartGarageFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNLmk8X_l91S4wVX3zUiGb9Y6LgEN-gNM',
    appId: '1:679017665841:web:19d33ab4ea7dcf4eb44c10',
    messagingSenderId: '679017665841',
    projectId: 'go-park-df349',
    authDomain: 'go-park-df349.firebaseapp.com',
    storageBucket: 'go-park-df349.firebasestorage.app',
    measurementId: 'G-BX0GDVP7LL',
  );
}
